unstable_features = true


blank_lines_upper_bound = 4
chain_width = 24
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
empty_item_single_line = false
enum_discrim_align_threshold = 24
fn_call_width = 0
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
short_array_element_width_threshold = 24
single_line_let_else_max_width = 0
struct_field_align_threshold = 48
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
